# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_house_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='city',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
