# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20170411_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='amount',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=5),
        ),
    ]
