# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20170411_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='amount',
            field=models.FloatField(),
        ),
    ]
