# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_auto_20170411_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='amount',
            field=models.FloatField(verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='house',
            name='city',
            field=models.CharField(max_length=15, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='house',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='house',
            name='gym',
            field=models.BooleanField(verbose_name='Gym'),
        ),
        migrations.AlterField(
            model_name='house',
            name='pet_allowed',
            field=models.BooleanField(verbose_name='Pet Allowed'),
        ),
        migrations.AlterField(
            model_name='house',
            name='room',
            field=models.PositiveSmallIntegerField(verbose_name='Room'),
        ),
        migrations.AlterField(
            model_name='house',
            name='sleep',
            field=models.PositiveSmallIntegerField(verbose_name='Sleep'),
        ),
        migrations.AlterField(
            model_name='house',
            name='swimming_pool',
            field=models.BooleanField(verbose_name='Swimming Pool'),
        ),
        migrations.AlterField(
            model_name='house',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Title'),
        ),
    ]
