# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_auto_20170411_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='city',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='gym',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='pet_allowed',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='room',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='sleep',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='swimming_pool',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
