# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_auto_20170411_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='location',
            field=models.CharField(choices=[('AMD', 'Ahmedabad'), ('BOM', 'Mumbai'), ('PNQ', 'Pune'), ('GOI', 'Goa'), ('BLR', 'Bangalore'), ('MAA', 'Chennai'), ('DEL', 'Delhi'), ('COK', 'Cochin'), ('CCJ', 'Calicut'), ('VTZ', 'Visakhapatnam'), ('GAU', 'Guwahati'), ('PAT', 'Patna'), ('IXC', 'Chandigarh'), ('RPR', 'Raipur'), ('NMB', 'Daman'), ('DIU', 'Diu'), ('SLV', 'Shimla'), ('IXJ', 'Jammu and Kashmir'), ('IXL', 'Ladakh')], max_length=30, null='True'),
        ),
    ]
