# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0023_auto_20170414_0846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['swimming_pool', 'gym', 'pet_allowed']},
        ),
    ]
