# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0024_auto_20170414_0847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={},
        ),
    ]
