# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0025_auto_20170414_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='air_conditioning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='alcohol',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='cook_on_call',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='house_keeping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='internet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='non_veg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='power_backup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='smoke',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='spa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='television',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='house',
            name='gym',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='house',
            name='pet_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='house',
            name='swimming_pool',
            field=models.BooleanField(default=False),
        ),
    ]
