# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0026_auto_20170415_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='amount',
            field=models.FloatField(verbose_name='Amount (in INR)'),
        ),
    ]
