# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0027_auto_20170415_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='bathroom',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='house',
            name='bedroom',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='house',
            name='room',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='house',
            name='sleep',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
