# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0028_auto_20170415_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='location',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
