# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0029_house_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='room',
        ),
        migrations.AlterField(
            model_name='house',
            name='amount',
            field=models.FloatField(verbose_name='Amount (in INR/night)'),
        ),
    ]
